/* ************************************************************************ */
/*         Queries to get counts of unique values by each column            */
/* ************************************************************************ */

/* ----------------- Teranet dataset with added columns ------------------- */

SELECT COUNT(*) AS num_rows,
       COUNT(DISTINCT transaction_id) AS transaction_id_unq,
       COUNT(DISTINCT lro_num) AS lro_num_unq,
       COUNT(DISTINCT pin) AS pin_unq,
       COUNT(DISTINCT consideration_amt) AS consideration_amt_unq,
       COUNT(DISTINCT registration_date) AS registration_date_unq,
       COUNT(DISTINCT postal_code) AS postal_code_unq,
       COUNT(DISTINCT unitno) AS unitno_unq,
       COUNT(DISTINCT street_name) AS street_name_unq,
       COUNT(DISTINCT street_designation) AS street_designation_unq,
       COUNT(DISTINCT street_direction) AS street_direction_unq,
       COUNT(DISTINCT municipality) AS municipality_unq,
       COUNT(DISTINCT street_number) AS street_number_unq,
       COUNT(DISTINCT x) AS x_unq,
       COUNT(DISTINCT y) AS y_unq,
       COUNT(DISTINCT objectid) AS objectid_unq,
       COUNT(DISTINCT dauid) AS dauid_unq,
       COUNT(DISTINCT csdname) AS csdname_unq,
       COUNT(DISTINCT street_name_raw) AS street_name_raw_unq,
       COUNT(DISTINCT date_disp) AS date_disp_unq,
       COUNT(DISTINCT price_disp) AS price_disp_unq,
       COUNT(DISTINCT year) AS year_unq,
       COUNT(DISTINCT year3) AS year3_unq,
       COUNT(DISTINCT year5) AS year5_unq,
       COUNT(DISTINCT year10) AS year10_unq,
       COUNT(DISTINCT xy) AS xy_unq,
       COUNT(DISTINCT pin_total_sales) AS pin_total_sales_unq,
       COUNT(DISTINCT xy_total_sales) AS xy_total_sales_unq,
       COUNT(DISTINCT pin_prev_sales) AS pin_prev_sales_unq,
       COUNT(DISTINCT xy_prev_sales) AS xy_prev_sales_unq,
       COUNT(DISTINCT pin_price_cum_sum) AS pin_price_cum_sum_unq,
       COUNT(DISTINCT xy_price_cum_sum) AS xy_price_cum_sum_unq,
       COUNT(DISTINCT pin_price_pct_change) AS pin_price_pct_change_unq,
       COUNT(DISTINCT xy_price_pct_change) AS xy_price_pct_change_unq,
       COUNT(DISTINCT price_da_pct_change) AS price_da_pct_change_unq,
       COUNT(DISTINCT pin_years_since_last_sale) AS pin_years_since_last_sale_unq,
       COUNT(DISTINCT xy_years_since_last_sale) AS xy_years_since_last_sale_unq,
       COUNT(DISTINCT da_days_since_last_sale) AS da_days_since_last_sale_unq,
       COUNT(DISTINCT da_years_since_last_sale) AS da_years_since_last_sale_unq,
       COUNT(DISTINCT pin_sale_next_6m) AS pin_sale_next_6m_unq,
       COUNT(DISTINCT pin_sale_next_1y) AS pin_sale_next_1y_unq,
       COUNT(DISTINCT pin_sale_next_3y) AS pin_sale_next_3y_unq,
       COUNT(DISTINCT xy_sale_next_6m) AS xy_sale_next_6m_unq,
       COUNT(DISTINCT xy_sale_next_1y) AS xy_sale_next_1y_unq,
       COUNT(DISTINCT xy_sale_next_3y) AS xy_sale_next_3y_unq
FROM teranet;
